In [85]:
import math
import torch
from torch import nn
import torch.nn.functional as F
from einops import rearrange, repeat

In [86]:
embed_dim = 128

In [87]:
tokens = nn.Parameter(torch.randn(16, 512, embed_dim))
cls_token = nn.Parameter(torch.randn(1, 1, embed_dim))

In [88]:
batch_size, seq_length, embed_dim = tokens.size()
print('tokens shape: ',tokens.shape)
print('batch size shape: ', batch_size)
print('seq_length shape: ', seq_length)
print('embed_dim shape: ', embed_dim)
print(45 * '-')
print(tokens[0])
print(45 * '-')
print('cls-token shape: ', cls_token.shape)
print(45 * '-')
print(cls_token[0][0][0:3])

tokens shape:  torch.Size([16, 512, 128])
batch size shape:  16
seq_length shape:  512
embed_dim shape:  128
---------------------------------------------
tensor([[-0.2746, -0.3776,  0.4259,  ...,  0.8152,  0.5993, -0.9665],
        [ 0.3267, -0.2080,  1.8929,  ...,  1.0312,  1.7465,  1.3037],
        [ 1.4661,  0.2651, -0.7825,  ..., -1.5199, -0.6107,  1.6200],
        ...,
        [ 0.8229,  0.4300,  0.9586,  ..., -0.1277,  0.0460, -1.1217],
        [-2.9557, -0.9000, -0.4491,  ...,  0.6556,  0.3396, -0.3450],
        [ 1.8641, -0.4858, -1.8348,  ..., -1.2150, -0.0938,  0.1266]],
       grad_fn=<SelectBackward0>)
---------------------------------------------
cls-token shape:  torch.Size([1, 1, 128])
---------------------------------------------
tensor([-0.3989,  0.1063, -0.6347], grad_fn=<SliceBackward0>)


In [89]:
# Add cls_token to the beginning of tokens (in each batch)
print('expand cls_token to match batch dim: ', cls_token.expand(batch_size, -1, -1).shape)

tokens = torch.cat((cls_token.expand(batch_size, -1, -1), tokens), dim=1)
print('tokens shape: ',tokens.shape)

expand cls_token to match batch dim:  torch.Size([16, 1, 128])
tokens shape:  torch.Size([16, 513, 128])


In [91]:
print(cls_token[0][0][0:3])
print(tokens[0])

tensor([-0.3989,  0.1063, -0.6347], grad_fn=<SliceBackward0>)
tensor([[-0.3989,  0.1063, -0.6347,  ..., -0.1643, -0.4541, -1.0043],
        [-0.2746, -0.3776,  0.4259,  ...,  0.8152,  0.5993, -0.9665],
        [ 0.3267, -0.2080,  1.8929,  ...,  1.0312,  1.7465,  1.3037],
        ...,
        [ 0.8229,  0.4300,  0.9586,  ..., -0.1277,  0.0460, -1.1217],
        [-2.9557, -0.9000, -0.4491,  ...,  0.6556,  0.3396, -0.3450],
        [ 1.8641, -0.4858, -1.8348,  ..., -1.2150, -0.0938,  0.1266]],
       grad_fn=<SelectBackward0>)
